#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar\"'"
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_width          0.0
yabai -m config active_window_border_color   0xffeeff00
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# space labels
yabai -m space 1 --label cal
yabai -m space 2 --label chat
yabai -m space 3 --label logseq
yabai -m space 4 --label browser
yabai -m space 5 --label code
yabai -m space 6 --label finder
yabai -m space 7 --label vnc

# general space settings
yabai -m config layout                       bsp
# yabai -m config top_padding                  0.0
yabai -m config bottom_padding               0.0
yabai -m config left_padding                 0.0
yabai -m config right_padding                0.0
yabai -m config window_gap                   0.0 

yabai -m rule --add app="^Spotify.*$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calendar.*$" sticky=on layer=above manage=off

yabai -m signal --add event=display_changed action="yabai -m config top_padding 34"
echo "yabai configuration loaded.."
